name: Bug Report
description: File a bug report here

title: "[bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!!!

  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: Which PHP versions did you run your code?
      multiple: true
      options:
        - '7.3.0+'
        - '7.4.0+'
        - '8.0.0+'
        - '8.0.2+'
        - '8.1.0+'
    validations:
      required: true

  - type: dropdown
    id: node-version
    attributes:
      label: NodeJs Version
      description: Which NodeJS versions did you run your code?
      multiple: true
      options:
        - '14+'
        - '16+'
        - '18+'
    validations:
      required: true

  - type: dropdown
    id: operating-systems
    attributes:
      label: Which operating systems have you tested for this bug?
      description: You may select more than one.
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
