name: Bug Report
description: File a bug report here

title: "[BUG]: "
labels: ["bug"]

body:
  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: Which PHP versions did you run your code?
      multiple: true
      options:
        - '7.3'
        - '7.4'
        - '8.0'
        - '8.1'
    validations:
      required: true
