name: Bug Report
description: File a bug report here

title: "[bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!!!
  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: Which PHP versions did you run your code?
      multiple: true
      options:
        - '7.3'
        - '7.4'
        - '8.0'
        - '8.1'
    validations:
      required: true
