on:
  push:
    tags:
    - v1.[0-9]+.[0-9]+

name: 🚀 Deploy website from Release
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Setup NodeJS 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.DEPLOY_HOSTNAME }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        dry-run: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
